import{a as y,S as h}from"./assets/vendor-DxnlFHFt.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const L="48228691-89796883a04c0782a049fa841",w="https://pixabay.com/api/";async function b(t,o=1,r=15){const n=`${w}?key=${L}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${r}`,{data:e}=await y.get(n);return e}function S(t){const o=document.querySelector(".images-container"),r=t.map(({webformatURL:n,tags:e,likes:s,views:i,comments:m,downloads:p,largeImageURL:g})=>`
    <li class="image-card">
      <a href="${g}">
        <img src="${n}" alt="${e}" />
        <div class="image-info">
            <p><span>Likes:</span> ${s}</p>
            <p><span>Views:</span> ${i}</p>
            <p><span>Comments:</span> ${m}</p>
            <p><span>Downloads:</span> ${p}</p>
        </div>
      </a>
    </li>
    `).join("");o.insertAdjacentHTML("beforeend",r)}function c(t){const o=document.querySelector(".load-more");t?o.classList.remove("is-hidden"):o.classList.add("is-hidden")}function v(){iziToast.show({title:"Notice",message:"Sorry, there are no images matching your search query. Please try again."})}function u(){iziToast.show({title:"Notice",message:"We're sorry, but you've reached the end of search results."})}let l;function $(){l?l.refresh():l=new h(".images-container a")}let a=1,d="";document.addEventListener("DOMContentLoaded",()=>{const t=document.querySelector(".load-more"),o=document.querySelector(".search-form"),r=document.querySelector(".search-input"),n=document.querySelector(".loader");t.classList.add("is-hidden"),n.style.display="none",o.addEventListener("submit",async function(e){e.preventDefault(),d=r.value.trim(),d!==""&&(t.classList.add("is-hidden"),n.style.display="block",a=1,document.querySelector(".images-container").innerHTML="",await f(),n.style.display="none")}),t.addEventListener("click",async function(){a++,n.style.display="block",await f(),n.style.display="none",q()})});async function f(){try{const t=await b(d,a);t.hits.length===0?(v(),c(!1)):(S(t.hits),$(),a*15>=t.totalHits?(c(!1),u()):c(!0))}catch(t){console.log(t),u()}}function q(){const t=document.querySelector(".images-container img");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
